---
- name: Install iptables-persistent
  apt:
    name:
      - iptables-persistent
    state: present
    update_cache: yes
  become: yes

- name: Set INPUT policy to ACCEPT
  ansible.builtin.iptables:
    chain: INPUT
    policy: ACCEPT
  become: yes

- name: Configure INPUT chain
  include_tasks: chain.yaml
  vars:
    chain: INPUT
    public_tcp_ports: "{{ host_public_tcp_ports | default([]) }}"

- name: Configure DOCKER-USER chain
  include_tasks: chain.yaml
  vars:
    chain: DOCKER-USER
    public_tcp_ports: "{{ docker_public_tcp_ports | default([]) }}"
  when: ansible_host != "db-1"

- name: write iptables rules
  shell: |
    /sbin/iptables-save > /etc/iptables/rules.v4
  become: yes